// ============ 颜色选择库:静态数据(项目配色目录 + 推荐配色库) ============
// 由 colorLibraryPage.js 渲染。
// - PROJECT_COLOR_CATALOG:本项目界面实际使用的全部颜色(CSS 主题变量 + 模块固定色),
//   变量色可修改并实时应用到界面(appearance.js 的 colorOverrides 机制)。
// - RECOMMENDED_PALETTES:各类型 UI 推荐配色(深色/浅色/游戏/国风等),可一键应用为当前主题。

// ---------- 项目配色目录 ----------
// 字段:key=覆盖键(colorOverrides 使用,固定色为 null 不可覆盖);varName=CSS 变量名;
// label=语义名;cnName/enName=颜色名(按主题分 dark/light 两套);
// dark/light=该主题下的默认值;usage=什么模块什么位置在使用。
export const PROJECT_COLOR_CATALOG = [
  {
    id: 'theme', name: '主题变量色', overridable: true,
    desc: '全局主题 CSS 变量(:root 深色 / [data-theme=light] 浅色)。修改后立即应用到整个应用界面,重置可恢复主题默认。',
    colors: [
      { key: 'bg', varName: '--bg', label: '主背景', dark: { hex: '#1b1d23', cnName: '深空蓝灰', enName: 'Deep Slate' }, light: { hex: '#f3f4f7', cnName: '云雾白', enName: 'Cloud White' }, usage: '窗口底色:首页、资源列表、预览区外围的整页背景(body / #app)' },
      { key: 'bg2', varName: '--bg2', label: '面板背景', dark: { hex: '#22242b', cnName: '石墨面板', enName: 'Graphite Panel' }, light: { hex: '#ffffff', cnName: '纯白', enName: 'Pure White' }, usage: '顶栏工具栏、标签条、预览面板、对话框底色(.toolbar / .tabs / 模态框)' },
      { key: 'bg3', varName: '--bg3', label: '菜单悬浮背景', dark: { hex: '#2a2d36', cnName: '铁灰', enName: 'Iron Gray' }, light: { hex: '#e8eaef', cnName: '银灰', enName: 'Silver Gray' }, usage: '菜单/列表项鼠标悬停、卡片、按钮默认底色(--btn-bg 同源)' },
      { key: 'input-bg', varName: '--input-bg', label: '文本框背景', dark: { hex: '#2a2d36', cnName: '铁灰输入', enName: 'Iron Input' }, light: { hex: '#f0f1f4', cnName: '淡灰输入', enName: 'Light Input' }, usage: '文本输入框、下拉选择框、文本标签的背景色(独立于菜单悬浮背景)' },
      { key: 'bg4', varName: '--bg4', label: '悬停高亮', dark: { hex: '#333642', cnName: '暮云灰', enName: 'Dusk Gray' }, light: { hex: '#e8e8e8', cnName: '浅灰', enName: 'Light Gray' }, usage: '列表行、按钮、菜单项鼠标悬停(hover)高亮;右键菜单背景;当前选中节点背景' },
      { key: 'border', varName: '--border', label: '边框线', dark: { hex: '#343845', cnName: '铅灰线', enName: 'Lead Gray' }, light: { hex: '#d2d6df', cnName: '雾线灰', enName: 'Mist Line' }, usage: '卡片、输入框、按钮描边与分割线' },
      { key: 'tree-line', varName: '--tree-line', label: '树连接线', dark: { hex: '#3a3e4a', cnName: '青灰线', enName: 'Slate Line' }, light: { hex: '#c4c9d4', cnName: '灰蓝线', enName: 'Cadet Line' }, usage: '侧栏分类树 / 菜单树的层级折线连接线' },
      { key: 'text', varName: '--text', label: '主文字', dark: { hex: '#e6e8ee', cnName: '月白', enName: 'Moon White' }, light: { hex: '#1f2329', cnName: '墨黑', enName: 'Ink Black' }, usage: '标题、正文、按钮文字等主要文字色' },
      { key: 'text2', varName: '--text2', label: '次要文字', dark: { hex: '#9aa1b2', cnName: '雾蓝灰', enName: 'Mist Blue-Gray' }, light: { hex: '#6b7280', cnName: '石板灰', enName: 'Slate' }, usage: '说明文字、文件路径、时间与元信息' },
      { key: 'text3', varName: '--text3', label: '弱化文字', dark: { hex: '#6f7686', cnName: '烟灰', enName: 'Smoke Gray' }, light: { hex: '#9aa1ad', cnName: '银烟灰', enName: 'Ash Silver' }, usage: '占位提示(placeholder)、禁用态文字、辅助角标' },
      { key: 'accent', varName: '--accent', label: '强调色', dark: { hex: '#4f8cff', cnName: '晴空蓝', enName: 'Azure' }, light: { hex: '#2f6fe0', cnName: '宝蓝', enName: 'Sapphire' }, usage: '主按钮、选中态、焦点高亮、链接文字(系统设置「外观」可配置,本页覆盖优先级最高)' },
      { key: 'accent2', varName: '--accent2', label: '深强调色', dark: { hex: '#2f6fe0', cnName: '海军蓝', enName: 'Navy Blue' }, light: { hex: '#2f6fe0', cnName: '宝蓝', enName: 'Sapphire' }, usage: '主按钮(primary)底色、激活标签下划线;默认跟随强调色,本页可单独覆盖' },
      { key: 'danger', varName: '--danger', label: '危险红', dark: { hex: '#e5484d', cnName: '绯红', enName: 'Scarlet' }, light: { hex: '#d9363e', cnName: '石榴红', enName: 'Garnet' }, usage: '删除按钮、危险操作确认、错误提示文字' },
      { key: 'ok', varName: '--ok', label: '成功绿', dark: { hex: '#46a758', cnName: '翠绿', enName: 'Emerald' }, light: { hex: '#2e9e4b', cnName: '松绿', enName: 'Pine Green' }, usage: '成功提示、校验通过、可用状态标记' },
    ],
  },
  {
    id: 'todo', name: 'Todo 任务语义色', overridable: true,
    desc: 'Todo-List 模块的三态语义色(待办/进行中/已完成/危险),深浅主题各一套,浅色下降饱和提对比。',
    colors: [
      { key: 'st-todo', varName: '--st-todo', label: '待办 · 靛', dark: { hex: '#6366f1', cnName: '靛蓝', enName: 'Indigo' }, light: { hex: '#4f46e5', cnName: '深靛', enName: 'Deep Indigo' }, usage: 'Todo 列表/看板:待办状态标签与筛选高亮' },
      { key: 'st-prog', varName: '--st-prog', label: '进行中 · 琥珀', dark: { hex: '#f59e0b', cnName: '琥珀', enName: 'Amber' }, light: { hex: '#d97706', cnName: '焦琥珀', enName: 'Burnt Amber' }, usage: 'Todo 列表/看板:进行中状态标签' },
      { key: 'st-done', varName: '--st-done', label: '已完成 · 绿', dark: { hex: '#22c55e', cnName: '荧光绿', enName: 'Vivid Green' }, light: { hex: '#16a34a', cnName: '常青绿', enName: 'Evergreen' }, usage: 'Todo 列表/看板:已完成状态标签' },
      { key: 'st-danger', varName: '--st-danger', label: '危险 · 亮红', dark: { hex: '#ef4444', cnName: '亮红', enName: 'Bright Red' }, light: { hex: '#dc2626', cnName: '朱红', enName: 'Vermilion' }, usage: 'Todo 列表/看板:过期与高优先级(危险)标记' },
    ],
  },
  {
    id: 'fixed', name: '模块固定色(仅查阅取色)', overridable: false,
    desc: '各模块内写死的功能色,不走主题变量;此处收录用于查阅数值、取色与收藏(不能覆盖应用)。',
    colors: [
      { key: null, varName: '', label: '收藏星标黄', hex: '#ffc53d', cnName: '琥珀黄', enName: 'Amber Yellow', usage: '收藏夹/列表星标按钮点亮色(.icon-btn.fav-on),首页收藏入口' },
      { key: null, varName: '', label: '图片资源橙', hex: '#e5a54b', cnName: '赭橙', enName: 'Ochre Orange', usage: '首页图片统计卡左边条、图片分类/资源类型图标色' },
      { key: null, varName: '', label: '音频资源紫', hex: '#b28df0', cnName: '鸢尾紫', enName: 'Iris Purple', usage: '首页音频统计卡左边条、音频空态大图标' },
      { key: null, varName: '', label: '图集徽章紫', hex: '#c9a8ff', cnName: '丁香紫', enName: 'Lilac', usage: '图集 / 音频类型徽章(type-badge)文字色' },
      { key: null, varName: '', label: '模式按钮蓝', hex: '#8ab4ff', cnName: '长春花蓝', enName: 'Periwinkle', usage: 'Markdown / HTML 编辑器模式按钮(分栏/预览/编辑)激活文字色' },
      { key: null, varName: '', label: '警示金', hex: '#e0a020', cnName: '警示金', enName: 'Warning Gold', usage: '工具批量处理结果警告文字、Spine 诊断 issues 警告标签/摘要框' },
      { key: null, varName: '', label: 'Markdown 错误红', hex: '#e0573c', cnName: '砖红', enName: 'Brick Red', usage: 'Markdown 编辑器错误提示、查找栏关闭按钮悬停' },
      { key: null, varName: '', label: '调试琥珀', hex: '#b76e00', cnName: '深琥珀', enName: 'Dark Amber', usage: '顶栏「🐞 调试」按钮开启态底色(暂停态另用 #7a1f1f 红)' },
      { key: null, varName: '', label: '强调兜底蓝', hex: '#6fb3ff', cnName: '晨光蓝', enName: 'Morning Blue', usage: 'accent2 变量的 CSS 兜底值(var 第二参数),正常不生效,供取色参考' },
    ],
  },
];

// ---------- 推荐配色库 ----------
// 每套配色 = 完整的一组主题角色色。colors[].role 与项目变量对应:
//   bg/bg2/bg3/bg4/border/tree-line/text/text2/text3/accent/accent2/danger/ok
// 应用为主题时:前 11 个基础角色写入当前主题设置,其余角色写入颜色覆盖(colorOverrides)。
export const RECOMMENDED_PALETTES = [
  {
    id: 'midnight-pro', typeName: '深色 · 专业工具', name: '午夜专业蓝', nameEn: 'Midnight Pro',
    desc: '类 VS Code 的沉稳深蓝灰,对比柔和,适合开发工具与资源管理类桌面应用长时间使用。',
    colors: [
      { role: 'bg', hex: '#11151c', cnName: '午夜藏蓝', enName: 'Midnight Navy', usage: '窗口底色 / 全页背景' },
      { role: 'bg2', hex: '#171c26', cnName: '暗夜面板', enName: 'Night Panel', usage: '顶栏 · 标签条 · 预览面板' },
      { role: 'bg3', hex: '#1e2530', cnName: '石墨卡片', enName: 'Graphite Card', usage: '侧栏菜单 · 卡片 · 按钮底' },
      { role: 'bg4', hex: '#2a3342', cnName: '悬停蓝灰', enName: 'Hover Slate', usage: '行 / 按钮悬停高亮' },
      { role: 'border', hex: '#303b4d', cnName: '钢蓝线', enName: 'Steel Line', usage: '描边 · 分割线' },
      { role: 'tree-line', hex: '#38455a', cnName: '青钢线', enName: 'Cadet Steel', usage: '侧栏树连接线' },
      { role: 'text', hex: '#e3e8f0', cnName: '霜白', enName: 'Frost White', usage: '标题与正文' },
      { role: 'text2', hex: '#97a3b6', cnName: '雾蓝灰', enName: 'Mist Blue-Gray', usage: '次要说明 · 路径' },
      { role: 'text3', hex: '#66748c', cnName: '烟蓝灰', enName: 'Smoke Blue', usage: '占位提示 · 禁用文字' },
      { role: 'accent', hex: '#4f8cff', cnName: '晴空蓝', enName: 'Azure', usage: '主按钮 · 选中 · 焦点' },
      { role: 'accent2', hex: '#2f6fe0', cnName: '海军蓝', enName: 'Navy', usage: '主按钮底 · 激活下划线' },
      { role: 'danger', hex: '#e5484d', cnName: '绯红', enName: 'Scarlet', usage: '删除 · 错误' },
      { role: 'ok', hex: '#46a758', cnName: '翠绿', enName: 'Emerald', usage: '成功 · 校验通过' },
    ],
  },
  {
    id: 'neon-arcade', typeName: '深色 · 游戏大厅', name: '游戏霓虹紫', nameEn: 'Neon Arcade',
    desc: '紫罗兰基底 + 高饱和霓虹强调,游戏平台 / 二次元工具气质,深色下光感强烈。',
    colors: [
      { role: 'bg', hex: '#12101d', cnName: '暗夜紫黑', enName: 'Void Purple', usage: '窗口底色 / 全页背景' },
      { role: 'bg2', hex: '#181430', cnName: '暗紫面板', enName: 'Deep Violet', usage: '顶栏 · 标签条 · 预览面板' },
      { role: 'bg3', hex: '#201a3e', cnName: '鸢尾卡片', enName: 'Iris Card', usage: '侧栏菜单 · 卡片 · 按钮底' },
      { role: 'bg4', hex: '#2c2352', cnName: '悬停紫', enName: 'Hover Violet', usage: '行 / 按钮悬停高亮' },
      { role: 'border', hex: '#362a63', cnName: '紫晶线', enName: 'Amethyst Line', usage: '描边 · 分割线' },
      { role: 'tree-line', hex: '#3e3173', cnName: '暗水晶线', enName: 'Onyx Crystal', usage: '侧栏树连接线' },
      { role: 'text', hex: '#ece8ff', cnName: '薰衣草白', enName: 'Lavender White', usage: '标题与正文' },
      { role: 'text2', hex: '#a89fd0', cnName: '雾紫', enName: 'Mist Lilac', usage: '次要说明 · 路径' },
      { role: 'text3', hex: '#746a9e', cnName: '烟紫', enName: 'Smoke Mauve', usage: '占位提示 · 禁用文字' },
      { role: 'accent', hex: '#8b5cf6', cnName: '霓虹紫', enName: 'Neon Violet', usage: '主按钮 · 选中 · 焦点' },
      { role: 'accent2', hex: '#6d28d9', cnName: '深葡萄紫', enName: 'Grape', usage: '主按钮底 · 激活下划线' },
      { role: 'danger', hex: '#f43f5e', cnName: '霓虹玫红', enName: 'Neon Rose', usage: '删除 · 错误' },
      { role: 'ok', hex: '#34d399', cnName: '霓虹薄荷', enName: 'Neon Mint', usage: '成功 · 校验通过' },
    ],
  },
  {
    id: 'pure-black', typeName: '深色 · OLED 极简', name: 'OLED 纯黑极简', nameEn: 'Pure Black Minimal',
    desc: '真纯黑基底(OLED 省电)+ 低饱和灰阶层次,中性强调色,极简黑白灰风格。',
    colors: [
      { role: 'bg', hex: '#000000', cnName: '纯黑', enName: 'Pure Black', usage: '窗口底色 / 全页背景' },
      { role: 'bg2', hex: '#0d0d0f', cnName: '碳黑面板', enName: 'Carbon Panel', usage: '顶栏 · 标签条 · 预览面板' },
      { role: 'bg3', hex: '#17171b', cnName: '碳灰卡片', enName: 'Carbon Card', usage: '侧栏菜单 · 卡片 · 按钮底' },
      { role: 'bg4', hex: '#24242b', cnName: '悬停灰', enName: 'Hover Gray', usage: '行 / 按钮悬停高亮' },
      { role: 'border', hex: '#2b2b33', cnName: '石墨线', enName: 'Graphite Line', usage: '描边 · 分割线' },
      { role: 'tree-line', hex: '#33333d', cnName: '暗灰线', enName: 'Charcoal Line', usage: '侧栏树连接线' },
      { role: 'text', hex: '#f2f3f5', cnName: '雪白', enName: 'Snow White', usage: '标题与正文' },
      { role: 'text2', hex: '#9b9ea8', cnName: '银灰', enName: 'Silver Gray', usage: '次要说明 · 路径' },
      { role: 'text3', hex: '#63666f', cnName: '铁灰', enName: 'Iron Gray', usage: '占位提示 · 禁用文字' },
      { role: 'accent', hex: '#d4d4d8', cnName: '冷白', enName: 'Cool White', usage: '主按钮 · 选中 · 焦点' },
      { role: 'accent2', hex: '#a1a1aa', cnName: '锌灰', enName: 'Zinc', usage: '主按钮底 · 激活下划线' },
      { role: 'danger', hex: '#ef4444', cnName: '亮红', enName: 'Bright Red', usage: '删除 · 错误' },
      { role: 'ok', hex: '#4ade80', cnName: '荧光绿', enName: 'Vivid Green', usage: '成功 · 校验通过' },
    ],
  },
  {
    id: 'tech-console', typeName: '深色 · 科技控制台', name: '科技蓝控制台', nameEn: 'Tech Console',
    desc: '深海蓝黑基底 + 青色霓虹强调,运维仪表盘 / 数据监控类界面气质。',
    colors: [
      { role: 'bg', hex: '#0d1420', cnName: '深海蓝黑', enName: 'Abyss Blue', usage: '窗口底色 / 全页背景' },
      { role: 'bg2', hex: '#122032', cnName: '深海面板', enName: 'Deep Sea Panel', usage: '顶栏 · 标签条 · 预览面板' },
      { role: 'bg3', hex: '#16293f', cnName: '浪影卡片', enName: 'Wave Card', usage: '侧栏菜单 · 卡片 · 按钮底' },
      { role: 'bg4', hex: '#1e3a56', cnName: '悬停浪蓝', enName: 'Hover Wave', usage: '行 / 按钮悬停高亮' },
      { role: 'border', hex: '#274a6b', cnName: '浪线蓝', enName: 'Tide Line', usage: '描边 · 分割线' },
      { role: 'tree-line', hex: '#2d5478', cnName: '深海线', enName: 'Ocean Line', usage: '侧栏树连接线' },
      { role: 'text', hex: '#dfeaf5', cnName: '冰晶白', enName: 'Ice White', usage: '标题与正文' },
      { role: 'text2', hex: '#8fa8c2', cnName: '雾海蓝', enName: 'Mist Sea', usage: '次要说明 · 路径' },
      { role: 'text3', hex: '#5d7590', cnName: '烟海蓝', enName: 'Smoke Sea', usage: '占位提示 · 禁用文字' },
      { role: 'accent', hex: '#22d3ee', cnName: '霓虹青', enName: 'Neon Cyan', usage: '主按钮 · 选中 · 焦点' },
      { role: 'accent2', hex: '#0891b2', cnName: '深青', enName: 'Deep Cyan', usage: '主按钮底 · 激活下划线' },
      { role: 'danger', hex: '#fb7185', cnName: '霓虹粉', enName: 'Neon Pink', usage: '删除 · 错误' },
      { role: 'ok', hex: '#4ade80', cnName: '荧光绿', enName: 'Vivid Green', usage: '成功 · 校验通过' },
    ],
  },
  {
    id: 'warm-night', typeName: '深色 · 暖夜护眼', name: '暖夜咖啡', nameEn: 'Warm Night Coffee',
    desc: '棕褐暖色基底,降低蓝光刺激,夜间阅读 / 资料整理场景更护眼。',
    colors: [
      { role: 'bg', hex: '#191512', cnName: '夜咖黑', enName: 'Espresso Night', usage: '窗口底色 / 全页背景' },
      { role: 'bg2', hex: '#211b17', cnName: '咖啡面板', enName: 'Coffee Panel', usage: '顶栏 · 标签条 · 预览面板' },
      { role: 'bg3', hex: '#2a231d', cnName: '摩卡卡片', enName: 'Mocha Card', usage: '侧栏菜单 · 卡片 · 按钮底' },
      { role: 'bg4', hex: '#38302a', cnName: '悬停可可', enName: 'Hover Cocoa', usage: '行 / 按钮悬停高亮' },
      { role: 'border', hex: '#453a31', cnName: '榛木线', enName: 'Hazelnut Line', usage: '描边 · 分割线' },
      { role: 'tree-line', hex: '#4e4237', cnName: '焦糖线', enName: 'Caramel Line', usage: '侧栏树连接线' },
      { role: 'text', hex: '#f0e7dc', cnName: '奶泡白', enName: 'Milk Foam', usage: '标题与正文' },
      { role: 'text2', hex: '#b3a695', cnName: '燕麦灰', enName: 'Oatmeal Gray', usage: '次要说明 · 路径' },
      { role: 'text3', hex: '#7d7263', cnName: '烟褐', enName: 'Smoke Umber', usage: '占位提示 · 禁用文字' },
      { role: 'accent', hex: '#d98e32', cnName: '焦糖橙', enName: 'Caramel Orange', usage: '主按钮 · 选中 · 焦点' },
      { role: 'accent2', hex: '#b26a1b', cnName: '深焦糖', enName: 'Dark Caramel', usage: '主按钮底 · 激活下划线' },
      { role: 'danger', hex: '#e0573c', cnName: '砖红', enName: 'Brick Red', usage: '删除 · 错误' },
      { role: 'ok', hex: '#7cae5a', cnName: '橄榄绿', enName: 'Olive Green', usage: '成功 · 校验通过' },
    ],
  },
  {
    id: 'clean-office', typeName: '浅色 · 清爽办公', name: '清爽办公白', nameEn: 'Clean Office',
    desc: '标准浅色办公风:纯白面板 + 冷灰底 + 商务蓝强调,信息密度高的管理界面首选。',
    colors: [
      { role: 'bg', hex: '#f5f6f8', cnName: '冷雾白', enName: 'Cool Mist', usage: '窗口底色 / 全页背景' },
      { role: 'bg2', hex: '#ffffff', cnName: '纯白', enName: 'Pure White', usage: '顶栏 · 标签条 · 预览面板' },
      { role: 'bg3', hex: '#eceef2', cnName: '浅银灰', enName: 'Pale Silver', usage: '侧栏菜单 · 卡片 · 按钮底' },
      { role: 'bg4', hex: '#dfe3ea', cnName: '悬停银', enName: 'Hover Silver', usage: '行 / 按钮悬停高亮' },
      { role: 'border', hex: '#d7dbe3', cnName: '银线', enName: 'Silver Line', usage: '描边 · 分割线' },
      { role: 'tree-line', hex: '#c9cfd9', cnName: '灰蓝线', enName: 'Cadet Line', usage: '侧栏树连接线' },
      { role: 'text', hex: '#1f2430', cnName: '墨蓝黑', enName: 'Ink Navy', usage: '标题与正文' },
      { role: 'text2', hex: '#5b6472', cnName: '石板灰', enName: 'Slate', usage: '次要说明 · 路径' },
      { role: 'text3', hex: '#98a0ad', cnName: '银烟灰', enName: 'Ash Silver', usage: '占位提示 · 禁用文字' },
      { role: 'accent', hex: '#2f6fe0', cnName: '宝蓝', enName: 'Sapphire', usage: '主按钮 · 选中 · 焦点' },
      { role: 'accent2', hex: '#1f5fd0', cnName: '深宝蓝', enName: 'Deep Sapphire', usage: '主按钮底 · 激活下划线' },
      { role: 'danger', hex: '#d9363e', cnName: '石榴红', enName: 'Garnet', usage: '删除 · 错误' },
      { role: 'ok', hex: '#2e9e4b', cnName: '松绿', enName: 'Pine Green', usage: '成功 · 校验通过' },
    ],
  },
  {
    id: 'warm-paper', typeName: '浅色 · 暖纸阅读', name: '暖纸阅读', nameEn: 'Warm Paper',
    desc: '米黄纸张底色 + 赭陶强调,类纸护眼,文档 / 长文阅读编辑场景友好。',
    colors: [
      { role: 'bg', hex: '#f7f1e5', cnName: '宣纸米', enName: 'Rice Paper', usage: '窗口底色 / 全页背景' },
      { role: 'bg2', hex: '#fffaf0', cnName: '米白', enName: 'Cream White', usage: '顶栏 · 标签条 · 预览面板' },
      { role: 'bg3', hex: '#f0e7d6', cnName: '亚麻卡片', enName: 'Linen Card', usage: '侧栏菜单 · 卡片 · 按钮底' },
      { role: 'bg4', hex: '#e5dac4', cnName: '悬停米金', enName: 'Hover Cream', usage: '行 / 按钮悬停高亮' },
      { role: 'border', hex: '#ded2ba', cnName: '沙线', enName: 'Sand Line', usage: '描边 · 分割线' },
      { role: 'tree-line', hex: '#d1c4a8', cnName: '驼线', enName: 'Camel Line', usage: '侧栏树连接线' },
      { role: 'text', hex: '#3b3227', cnName: '烟墨褐', enName: 'Ink Umber', usage: '标题与正文' },
      { role: 'text2', hex: '#7a6d5c', cnName: '驼灰', enName: 'Camel Gray', usage: '次要说明 · 路径' },
      { role: 'text3', hex: '#a89a86', cnName: '沙灰', enName: 'Sand Gray', usage: '占位提示 · 禁用文字' },
      { role: 'accent', hex: '#bc6c3d', cnName: '赭陶橙', enName: 'Terracotta', usage: '主按钮 · 选中 · 焦点' },
      { role: 'accent2', hex: '#9a5530', cnName: '深赭', enName: 'Deep Terracotta', usage: '主按钮底 · 激活下划线' },
      { role: 'danger', hex: '#c0392b', cnName: '赤陶红', enName: 'Terra Red', usage: '删除 · 错误' },
      { role: 'ok', hex: '#4d8b4f', cnName: '苔绿', enName: 'Moss Green', usage: '成功 · 校验通过' },
    ],
  },
  {
    id: 'mint-fresh', typeName: '浅色 · 薄荷清新', name: '薄荷清新', nameEn: 'Mint Fresh',
    desc: '薄荷绿浅底 + 翡翠强调,清新轻盈,适合内容展示 / 儿童教育类轻快界面。',
    colors: [
      { role: 'bg', hex: '#f0f7f4', cnName: '薄荷雾白', enName: 'Mint Mist', usage: '窗口底色 / 全页背景' },
      { role: 'bg2', hex: '#ffffff', cnName: '纯白', enName: 'Pure White', usage: '顶栏 · 标签条 · 预览面板' },
      { role: 'bg3', hex: '#e3efe9', cnName: '浅薄荷', enName: 'Pale Mint', usage: '侧栏菜单 · 卡片 · 按钮底' },
      { role: 'bg4', hex: '#d3e6dd', cnName: '悬停薄荷', enName: 'Hover Mint', usage: '行 / 按钮悬停高亮' },
      { role: 'border', hex: '#c8dfd4', cnName: '薄荷线', enName: 'Mint Line', usage: '描边 · 分割线' },
      { role: 'tree-line', hex: '#b9d4c7', cnName: '灰绿线', enName: 'Sage Line', usage: '侧栏树连接线' },
      { role: 'text', hex: '#1d332b', cnName: '墨绿黑', enName: 'Ink Green', usage: '标题与正文' },
      { role: 'text2', hex: '#547266', cnName: '鼠尾草绿', enName: 'Sage Green', usage: '次要说明 · 路径' },
      { role: 'text3', hex: '#8ba89c', cnName: '烟绿', enName: 'Smoke Green', usage: '占位提示 · 禁用文字' },
      { role: 'accent', hex: '#0f9d76', cnName: '翡翠绿', enName: 'Jade Green', usage: '主按钮 · 选中 · 焦点' },
      { role: 'accent2', hex: '#0b7d5f', cnName: '深翡翠', enName: 'Deep Jade', usage: '主按钮底 · 激活下划线' },
      { role: 'danger', hex: '#d9363e', cnName: '石榴红', enName: 'Garnet', usage: '删除 · 错误' },
      { role: 'ok', hex: '#2e9e4b', cnName: '松绿', enName: 'Pine Green', usage: '成功 · 校验通过' },
    ],
  },
  {
    id: 'vivid-orange', typeName: '浅色 · 活力闯关', name: '活力闯关橙', nameEn: 'Vivid Energy',
    desc: '暖奶油底 + 高饱和活力橙,儿童学习 / 游戏闯关类界面(如得乐学苑)气质。',
    colors: [
      { role: 'bg', hex: '#fff8f0', cnName: '奶油白', enName: 'Cream', usage: '窗口底色 / 全页背景' },
      { role: 'bg2', hex: '#ffffff', cnName: '纯白', enName: 'Pure White', usage: '顶栏 · 标签条 · 预览面板' },
      { role: 'bg3', hex: '#ffeede', cnName: '蜜桃卡片', enName: 'Peach Card', usage: '侧栏菜单 · 卡片 · 按钮底' },
      { role: 'bg4', hex: '#ffe0c7', cnName: '悬停杏', enName: 'Hover Apricot', usage: '行 / 按钮悬停高亮' },
      { role: 'border', hex: '#f7d4b0', cnName: '杏黄线', enName: 'Apricot Line', usage: '描边 · 分割线' },
      { role: 'tree-line', hex: '#f0c49a', cnName: '蜜糖线', enName: 'Honey Line', usage: '侧栏树连接线' },
      { role: 'text', hex: '#45301f', cnName: '深可可', enName: 'Dark Cocoa', usage: '标题与正文' },
      { role: 'text2', hex: '#8a6b52', cnName: '浅可可', enName: 'Light Cocoa', usage: '次要说明 · 路径' },
      { role: 'text3', hex: '#b59a81', cnName: '焦糖灰', enName: 'Caramel Gray', usage: '占位提示 · 禁用文字' },
      { role: 'accent', hex: '#ff7a1a', cnName: '活力橙', enName: 'Vivid Orange', usage: '主按钮 · 选中 · 焦点' },
      { role: 'accent2', hex: '#e05e00', cnName: '深焰橙', enName: 'Deep Flame', usage: '主按钮底 · 激活下划线' },
      { role: 'danger', hex: '#e53e3e', cnName: '亮红', enName: 'Bright Red', usage: '删除 · 错误' },
      { role: 'ok', hex: '#38a169', cnName: '草绿', enName: 'Grass Green', usage: '成功 · 校验通过' },
    ],
  },
  {
    id: 'indigo-mist', typeName: '浅色 · 黛青国风', name: '黛青国风', nameEn: 'Indigo Mist',
    desc: '取中国传统色「黛」「青」意象:青灰纸底 + 黛青强调,沉静素雅的国风界面。',
    colors: [
      { role: 'bg', hex: '#f2f4f3', cnName: '月白纸', enName: 'Moon Paper', usage: '窗口底色 / 全页背景' },
      { role: 'bg2', hex: '#fbfcfb', cnName: '缟白', enName: 'Silk White', usage: '顶栏 · 标签条 · 预览面板' },
      { role: 'bg3', hex: '#e8edeb', cnName: '青灰卡', enName: 'Cyan-Green Card', usage: '侧栏菜单 · 卡片 · 按钮底' },
      { role: 'bg4', hex: '#d9e2df', cnName: '悬停青雾', enName: 'Hover Mist', usage: '行 / 按钮悬停高亮' },
      { role: 'border', hex: '#cfd9d5', cnName: '青白线', enName: 'Cyan Line', usage: '描边 · 分割线' },
      { role: 'tree-line', hex: '#c2cec9', cnName: '黛灰线', enName: 'Daisy Line', usage: '侧栏树连接线' },
      { role: 'text', hex: '#22302c', cnName: '黛墨', enName: 'Ink Teal', usage: '标题与正文' },
      { role: 'text2', hex: '#5c6f69', cnName: '青灰', enName: 'Cyan-Green Gray', usage: '次要说明 · 路径' },
      { role: 'text3', hex: '#93a5a0', cnName: '烟青', enName: 'Smoke Teal', usage: '占位提示 · 禁用文字' },
      { role: 'accent', hex: '#2f6f6a', cnName: '黛青', enName: 'Indigo Teal', usage: '主按钮 · 选中 · 焦点' },
      { role: 'accent2', hex: '#235a56', cnName: '深黛', enName: 'Deep Indigo', usage: '主按钮底 · 激活下划线' },
      { role: 'danger', hex: '#c0392b', cnName: '朱砂红', enName: 'Cinnabar', usage: '删除 · 错误' },
      { role: 'ok', hex: '#5b8c5a', cnName: '竹青绿', enName: 'Bamboo Green', usage: '成功 · 校验通过' },
    ],
  },
];
